name: mobile_app
description: "My auto-gen project"

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.0.10
  json_annotation: ^4.8.0
  swagger_dart_code_generator: ^2.14.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  chopper_generator: ^7.0.7
  json_serializable: ^6.6.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true